# This is a basic workflow to help you get started with Actions

name: echo-host

on: [push]
jobs:
  echo-host:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        shell: bash
        run: cat /etc/os-release | grep PRETTY_NAME 
             
      
