name: if-trial
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        shell: bash
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
             cat /etc/os-release | grep PRETTY_NAME
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
             echo "value=$GITHUB_RUN_NUMBER" >> "$GITHUB_OUTPUT"
      - id: step3
             if: [[ "$OUTPUT1" == "hello" ]]  echo "tst=true" >> GITHUB_OUTPUT  else echo "tst=false" >> GITHUB_OUTPUT fi
